// Generated by CoffeeScript 1.7.1
(function() {
  var DomNodes, PEG, attachSiblings, fs, sys, upndown, util;

  fs = require('fs');

  sys = require('sys');

  util = require('util');

  PEG = require('pegjs');

  DomNodes = require('../lib/domnodes');

  upndown = require('../lib/upndown');

  attachSiblings = function(tree, parent) {
    var node, prevsibling, _i, _len, _results;
    prevsibling = null;
    _results = [];
    for (_i = 0, _len = tree.length; _i < _len; _i++) {
      node = tree[_i];
      if (prevsibling !== null) {
        prevsibling.setNextSibling(node);
      }
      node.setPreviousSibling(prevsibling);
      if (node.hasChilds()) {
        attachSiblings(node.getChildNodes());
      }
      _results.push(prevsibling = node);
    }
    return _results;
  };

  fs.readFile('src/html.pegjs', function(err, pegdata) {
    var PegHtmlParser;
    if (err) {
      throw err;
    }
    PegHtmlParser = PEG.buildParser(pegdata.toString());
    return fs.readFile('src/sample.medium.html', function(err, html) {
      var DOM, e, htmlstring, k, _i, _results;
      htmlstring = html.toString();
      _results = [];
      for (k = _i = 0; _i <= 10; k = ++_i) {
        console.log(k);
        try {
          _results.push(DOM = PegHtmlParser.parse(htmlstring));
        } catch (_error) {
          e = _error;
          _results.push(console.log(e));
        }
      }
      return _results;
    });
  });

}).call(this);
